
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend/deploy.yml
- frontend/service.yml
- backend/deploy.yml
- backend/service.yml
- ingress.yml
- argocd/application.yml
  

images:
- name: 042786454503.dkr.ecr.us-east-1.amazonaws.com/application/backend
  newName: 042786454503.dkr.ecr.us-east-1.amazonaws.com/application/backend
  newTag: 5dfbf6fc1c190328897ab855b5b8d7aec32437f5
- name: 042786454503.dkr.ecr.us-east-1.amazonaws.com/application/frontend
  newName: 042786454503.dkr.ecr.us-east-1.amazonaws.com/application/frontend
  newTag: 2e6f3f53f7ada873fdff2f0387268e0370791cfe
