
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend/deploy.yml
- frontend/service.yml
- backend/deploy.yml
- backend/service.yml
- ingress.yml
- argocd/application.yml
  

images:
- name: 042786454503.dkr.ecr.us-east-1.amazonaws.com/application/backend
  newName: 042786454503.dkr.ecr.us-east-1.amazonaws.com/application/backend
  newTag: 183e6fb1c8968513cbc98592fa7064e5797ee052
- name: 042786454503.dkr.ecr.us-east-1.amazonaws.com/application/frontend
  newName: 042786454503.dkr.ecr.us-east-1.amazonaws.com/application/frontend
  newTag: 183e6fb1c8968513cbc98592fa7064e5797ee052
